v44 Upgrade: Cosmos module migrations x/gov
Kava-Labs/kava pull request #1065
Opened 2021-11-17 19:40 UTC by DracoLi

## Summary
This PR sets up the migration cmd to be able to start a v16 migration. I've also did a POC migration of the x/gov module. We will still need to make sure we support the other cosmos modules but this should be a good starting point to start adding them.

Note:
- `kvd` is not migrated to v44 yet so we can't start the migration via cli until its upgrade.

## Testing
Regarding testing cosmos modules, I opted to just include a json of the app state that we want to test instead of creating separate versions for each test case in this PR. This saves time but does mean we will have a lot of test scenarios the json files instead of separated out (like in v15 migrations). 
I think it might be worth to do this for the cosmos modules while doing more deliberate separated tests for the kava modules. Love to get some opinions on this.

2021-11-19 20:16 UTC, DracoLi commented on migrate/v0_16/modules/cosmos_gov.go
> +	case v015kavadist.CommunityPoolMultiSpendProposal:
kavadist proposal

2021-12-06 16:07 UTC, rhuairahrighairidh requested changes
`kvd` is deprecated in favour of `kava` so the migration and assert-invariants cmd can be connected in.

I like the json tests for cosmos migrations, feels like a reasonable balance.

2021-12-06 18:15 UTC, DracoLi commented on migrate/v0_16/module.go
> +	appState = modules.MigrateCosmosAppState(appState, ctx)
👍  ill update this in a later PR since there are a few followup PRS that updates this.

2021-12-06 18:18 UTC, DracoLi commented on migrate/cmd.go
> +}
:+1: I'll update this to only migrate v15 -> v16

2021-12-06 18:19 UTC, DracoLi commented on migrate/v0_16/testdata/genesis-v16.json
> +{
yeah, not used here but will be used in a follow up PR. I suggest leaving it in to avoid a chain of conflicts.

2021-12-06 18:29 UTC, DracoLi commented
https://github.com/Kava-Labs/kava/pull/1065/commits/fc218ded4ff570adff667cbbfaa9b5bf0e5dbfcb
- added migrate genesis and assert invariant to `cmd/kava`
- Removed support for migrating any other versions aside from v15-16

2021-12-06 18:44 UTC, DracoLi commented on migrate/v0_16/module.go
> +	appState = modules.MigrateCosmosAppState(appState, ctx)
https://github.com/Kava-Labs/kava/pull/1092

2021-12-07 12:04 UTC, rhuairahrighairidh approved these changes
lgtm

2021-12-07 14:29 UTC, merged