EVM akava coins handling
Kava-Labs/kava pull request #1171
Opened 2022-02-17 20:34 UTC by DracoLi

Creating a BankKeeper wrapper for x/evm that only allows requests for the "akava" denom.

This bank keeper will convert `akava` request from x/evm to both the `ukava` and remaining `akava` needed. Then depending on the request, both `akava` and `ukava` denoms are used from the bank keeper to enable the use of both denoms as a single one.

Additional logic is also implemented to properly handle the minting of `akava` from `akava` and also converting extra `akava` to `ukava`.

2022-02-18 17:28 UTC, DracoLi commented on x/evmutils/keeper/bank_keeper.go
> +	return k.bk.SendCoinsFromAccountToModule(ctx, senderAddr, recipientModule, coins)
note: this module should never have enough akava for a ukava so we shouldn't need to do `convertAkavaToUkava` here

2022-02-25 04:31 UTC, karzak requested changes
Gave it a first pass - will give it another look after I use it with kvtool a bit more. 

Didn't find any issues with the implementation - just a few additional tests I'd like to see

2022-02-25 04:31 UTC, karzak commented on x/evmutils/keeper/bank_keeper.go
> +	// note: we should always have 1 coin here since coins cannot have dup denoms after we validate.
```suggestion
	// note: we should always have len(coins) == 1 here since coins cannot have dup denoms after we validate.
```

2022-02-27 18:58 UTC, DracoLi commented
working on a big update that tracks akava outside of bank keeper. closing this PR

2022-02-27 18:58 UTC, closed without merging