Update vaults to use sdk.Dec shares
Kava-Labs/kava pull request #1283
Opened 2022-08-02 22:23 UTC by drklee3

* Fixes share issuing for deposits after share value increases.
* User can withdraw with sdk.Coin amount and receive the requested amount.
* In some cases account value may be 1 coin less than deposited. Deposit 100, but account value is would be 99. This should be at max 1 ucoin, e.g. 1ukava or 0.000001 kava.

2022-08-08 21:13 UTC, DracoLi commented on x/earn/keeper/vault_share.go
> +	//               = assetAmount * (shareCount / totalTokens)
very useful explanation. small suggestion: I think we should update the vars here to match the vars used in the function.

2022-08-08 21:13 UTC, DracoLi commented on x/earn/keeper/vault_share.go
> +	// 100 * (100 / 101) == 100 * 0     == 0
if asset amount is 1, this will result in no shares. is that expected?

2022-08-08 21:13 UTC, DracoLi commented on x/earn/keeper/vault_share.go
> +	//               = assetAmount * (shareCount / totalTokens)
totalTokens should be totalValue right?

2022-08-08 21:24 UTC, DracoLi commented on x/earn/keeper/vault_share_test.go
> +			name: "multi step flow 1:1",
is this suppose to be a different test? Seems like the first 1:1 test

2022-09-09 17:00 UTC, rhuairahrighairidh requested changes
I think it's probably worth adding some tests for the `VaultShares` methods. If the current code is directly cloned from `DecCoins` it's probably correct. But tests are useful to catch regressions if we add features, or updgrade the sdk version.

2022-09-12 14:04 UTC, rhuairahrighairidh approved these changes

2022-09-12 16:23 UTC, merged