feat: add upgrade handlers for v0.24.x
Kava-Labs/kava pull request #1619
Opened 2023-06-06 21:56 UTC by pirtleshell

## Description
Adds mainnet & testnet upgrade handlers to initialize state for cosmos coin conversion functionality. Includes automated e2e tests for mainnet upgrade handler.

## Checklist
 - [x] ~~Changelog has been updated as necessary.~~

2023-06-14 17:18 UTC, galxy25 approved these changes

2023-06-14 18:03 UTC, galxy25 approved these changes

2023-06-14 18:06 UTC, galxy25 commented
re-ran the tests that failed due to i/o timeout talking to the docker registry

2023-06-15 15:34 UTC, nddeluca requested changes

2023-06-15 15:34 UTC, nddeluca commented on app/upgrades.go
> +	app.upgradeKeeper.SetUpgradeHandler(TestnetUpgradeName, TestnetUpgradeHandler(app))
Can we refactor these to pass the mainnet and testnet constants?  Then we can have one upgrade handler and keep the globals in this top level

2023-06-15 19:21 UTC, merged