Set the CDP Block Interval to 100 during v0.26.x upgrade
Kava-Labs/kava pull request #1865
Opened 2024-03-28 23:25 UTC by nddeluca

This updates the CDP parameters to have a liquidation block interval of 100, instead of the default value of 1.

Since the interest synchronization and the liquidation process makes up a substantial portion of block time, this has a significant impact on block execution performance.

The included E2E ensures that no other parameters are changed from before upgrade along with verifying that the liquidation interval is correctly set.

2024-03-28 23:32 UTC, nddeluca commented on tests/e2e/e2e_upgrade_handler_test.go
> +	suite.Require().Equal(expectedParams, paramsAfter.Params,
Tested that this failed when modifying another parameter beyond the block interval

2024-03-29 03:06 UTC, karzak commented
LGTM - Double checked in `x/cdp/abci_test.go` that we have coverage which shows that begin blocker runs only (and definitely runs) at `LiquidationBlockInterval - looked good.

2024-03-29 03:07 UTC, karzak approved these changes

2024-03-29 03:15 UTC, karzak commented
After a bit more thought, I would argue setting `LiquidationBlockInterval` to `50` instead `100` - `50` gives worst case of running roughly once every 6 minutes - this seems preferable to every 12 minutes in cases where there is a backlog of risky cdps. 

Thoughts @rhuairahrighairidh?

2024-03-29 03:16 UTC, karzak requested changes
See comment on updating the value - otherwise LGTM

2024-03-29 18:05 UTC, merged

2024-03-29 23:11 UTC, rhuairahrighairidh reviewed
looks good, agree with kevin the more frequent liquidations is a bit better