Golang linter
Kava-Labs/kava pull request #1977
Opened 2024-07-25 20:43 UTC by sesheffield

## Description
* adding a .golangci.yml file to dictate the golang linters.
* added a new make command
* added CODEOWNERS 

## Checklist
 - [ ] Changelog has been updated as necessary.

2024-07-25 21:31 UTC, pirtleshell requested changes
i appreciate your changes here. however, i think this PR is doing too much at once and should be broken into more singularly-focused pieces.

additionally your commit messages and PR descriptions should include details on why changes are being made and be more specific. for example "added a new make command", does not tell a reader of the git log what was actually changed. PR titles & commit messages should follow the guidelines outlined in https://www.conventionalcommits.org/en/v1.0.0/. Example: "feat(ci): enabled golang linters" (assuming this is the only thing the PR does, which is not the case for this PR).

regarding the linters: i think we need to first decide as a team what lints to use. i also think the final form of linting should prefer starting with the defaults and only adding or disabling functionality as the need arises, rather than starting with everything disabled and enabling individual linters/rules. this will also make the config file much simpler and easier to read. exceptions to the defaults, including additional new linters, should have explanatory comments in the config YAML.

some other thoughts/questions:
* please also delete the existing, incorrectly named config file
* please add @faddat as a co-author to the commit that changes the config file. he previously did a good amount of prep for the linters, including identifying the misnamed file in #1636 (thank you, @faddat!!)
* does the current codebase pass all these lints? are we sure the next commit to master won't fail CI because of things enabled here?

2024-07-25 21:31 UTC, pirtleshell commented on .github/workflows/ci-lint.yml
> +          echo "GOLANGCI_VERSION=v$(cat .golangci-version)"
i think you're going to end up with double `v`s in the env var here

2024-07-25 21:31 UTC, pirtleshell commented on .golangci-version
> +v1.59
nit: can you setup your editor to add newlines at the end of files?

2024-07-25 21:31 UTC, pirtleshell commented on .github/workflows/ci-lint.yml
> +          args: ./...
this should be added in a separate pr, and in a way that will not result in the master branch CI failing (make it only operate on a diff, disable rules that we break to be re-enabled one at a time in subsequent prs, or update code if it is very simple and obviously incorrect). 

if we break a rule that requires a meaningful & consequential change to the code, it should be made in a pr that highlights what is happening and why the change is safe.

on principle & to the best of our ability, we should never merge a commit that fails the PR CI or will break master's CI

2024-07-25 21:31 UTC, pirtleshell commented on .github/CODEOWNERS
> +* @rhuairahrighairidh @karzak @pirtleshell @drklee3 @nddeluca @DracoLi @evgeniy-scherbina @sesheffield
🏆 excellent add.
can you include a comment referencing [this](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners) for easy access/explanation of this for those not in the know?

2024-07-26 13:56 UTC, sesheffield commented
> i appreciate your changes here. however, i think this PR is doing too much at once and should be broken into more singularly-focused pieces.
> 
> additionally your commit messages and PR descriptions should include details on why changes are being made and be more specific. for example "added a new make command", does not tell a reader of the git log what was actually changed. PR titles & commit messages should follow the guidelines outlined in https://www.conventionalcommits.org/en/v1.0.0/. Example: "feat(ci): enabled golang linters" (assuming this is the only thing the PR does, which is not the case for this PR).
> 
> regarding the linters: i think we need to first decide as a team what lints to use. i also think the final form of linting should prefer starting with the defaults and only adding or disabling functionality as the need arises, rather than starting with everything disabled and enabling individual linters/rules. this will also make the config file much simpler and easier to read. exceptions to the defaults, including additional new linters, should have explanatory comments in the config YAML.
> 
> some other thoughts/questions:
> 
> * please also delete the existing, incorrectly named config file
> * please add @faddat as a co-author to the commit that changes the config file. he previously did a good amount of prep for the linters, including identifying the misnamed file in [Linters haven't been run recently #1636](https://github.com/Kava-Labs/kava/issues/1636) (thank you, @faddat!!)
> * does the current codebase pass all these lints? are we sure the next commit to master won't fail CI because of things enabled here?


1. please also delete the existing, incorrectly named config file
    * not sure what file you're referring to. 
2. please add @faddat as a co-author to the commit that changes the config file. he previously did a good amount of prep for the linters, including identifying the misnamed file in [Linters haven't been run recently #1636](https://github.com/Kava-Labs/kava/issues/1636) (thank you, @faddat!!)
    * not a valid codeowner [aa558db](https://github.com/Kava-Labs/kava/pull/1977/commits/aa558dbeddda48c6ac00ff20281bdfdc83bde59b)
3. does the current codebase pass all these lints? are we sure the next commit to master won't fail CI because of things enabled here?
    * [8944ae6](https://github.com/Kava-Labs/kava/pull/1977/commits/8944ae607b9c2489503bdfca2f1f330015a3da11)

2024-07-29 22:20 UTC, sesheffield commented
@pirtleshell 

> regarding the linters: i think we need to first decide as a team what lints to use. i also think the final form of linting should prefer starting with the defaults and only adding or disabling functionality as the need arises, rather than starting with everything disabled and enabling individual linters/rules. this will also make the config file much simpler and easier to read. exceptions to the defaults, including additional new linters, should have explanatory comments in the config YAML.

I agree that we should discuss and finalize the linters as a team. I can set up a time with the team to discuss this further. My approach was to add all linters initially, as I found that even the basic linters were failing, which made starting with a comprehensive setup more practical.

The linters currently enabled and disabled in the configuration align with the existing "style" the team has developed. Starting with all linters that we can have enabled allows us to identify and address any issues early on. Once we have a baseline where everything is passing, we can then adjust the configuration by enabling or disabling specific rules as needed. This approach will help us ensure that we maintain a high standard of code quality from the start.

I agree that the final configuration should be simplified and commented for clarity. Once we finalize the linters and rules, I'll make sure to document any exceptions and customizations in the config YAML.

Let me know if you have any specific linters or rules you'd like to prioritize, and we can adjust accordingly.

2024-07-31 20:12 UTC, pirtleshell commented on .golangci.yml
> +  exclude-rules:
can we remove the exclusions until they rear their ugly heads in future commits?

2024-07-31 20:13 UTC, pirtleshell approved these changes
looks great, thanks for the much needed addition!

2024-07-31 20:23 UTC, merged