[R4R] feat: add variable length lockups for incentive rewards
Kava-Labs/kava pull request #655
Opened 2020-09-17 21:55 UTC by karzak

2020-09-18 15:31 UTC, rhuairahrighairidh requested changes
Left some initial comments, otherwise looks good.

We might need to be careful with multipler factors so we don't run out of funds in the incentive account. If everyone chooses high lockup with high multiple then funds could be used up faster than we're expecting. But even if that happens claim msgs will just fail rather than anything worse.

2020-09-18 15:31 UTC, rhuairahrighairidh commented on x/incentive/handler.go
> +		err := k.PayoutClaim(ctx, claim.Owner, claim.CollateralType, claim.ClaimPeriodID, types.MultiplierName(strings.ToLower(msg.MultiplierName)))
nit: The multipler name is parsed here and in types.msgs. You could move the parsing to a func like `NewMultiplerNameFromString`

2020-09-18 15:31 UTC, rhuairahrighairidh commented on x/incentive/types/params.go
> +	MonthsLockup int            `json:"months_lockup" yaml:"months_lockup"`
`int` could introduce some indeterminsm over using `sdk.Int` or `int64`.
I think if someone's running a node on a super old 32 bit computer, golang uses int32 as the underlying type for int. Whereas on modern machines it uses int64.

2020-09-18 15:35 UTC, karzak commented on x/incentive/keeper/payout.go
> +	length := ctx.BlockTime().AddDate(0, multiplier.MonthsLockup, 0).Unix()
good catch, this should be `ctx.BlockTime().AddDate(0, multiplier.MonthsLockup, 0).Unix() - ctx.BlockTime().Unix()`

2020-09-21 20:12 UTC, rhuairahrighairidh approved these changes
looks good

2020-09-21 20:20 UTC, merged