[R4R] fix: close expired auctions in init genesis
Kava-Labs/kava pull request #668
Opened 2020-09-26 14:18 UTC by karzak

If an auction expires during migration, auction invariants will panic when the chain tries to restart. Fix is to close expired auctions in init genesis.

2020-09-30 08:50 UTC, denalimarsh commented
If I understand correctly:
1. Auctions expiring during migration causes panic
2. We're closing all already expired Auctions before migration

Doesn't this mean that any active Auctions will not be closed before migration and could still expire during migration?

What's the current sequence of manually triggered CDP/Auction module events for the migration? We can mitigate this issue by pausing CDP liquidations before migration and waiting until all Auctions have expired before proceeding with the migration, but in that case, this code addition is redundant.

2020-10-01 14:02 UTC, rhuairahrighairidh commented
Looks like this will panic if a debt auction expires during migration.
When a debt auction closes, `supplykeeper.MintCoins` is called, which calls `supplykeeper.GetSupply` which will panic as supply's init genesis hasn't run yet.

2020-10-01 14:13 UTC, rhuairahrighairidh requested changes
Looks like this will panic if a debt auction expires during migration.
When a debt auction closes, supplykeeper.MintCoins is called, which calls supplykeeper.GetSupply which will panic as  the current supply hasn't been set yet by supply's init genesis.

2020-10-01 23:24 UTC, rhuairahrighairidh approved these changes
looks good

2020-10-02 16:50 UTC, merged