Harvest: multiple deposits
Kava-Labs/kava pull request #711
Opened 2020-11-03 15:13 UTC by denalimarsh

This PR addresses the ticket "Steven Borrows a Single Asset, Supplying Multiple Assets".

- Over the next few cards I'll be thinking about a way to gracefully reconcile the `calculateUSDValue` and `getBorrowableAmountForDeposit` functions.
- It might make sense to add a new struct `asset{denom, conversionFactor, price, loanToValue}` to the test suite. Didn't add here as it wasn't necessary for acceptance criteria.

Acceptance criteria changes:
- Removed superfluous mentions of BUSD
- Changed amount of USDX preloaded onto the Harvest module account from 100 USDX to 200 USDX

2020-11-03 16:01 UTC, karzak requested changes
Variable name accuracy is the only blocking requested change, otherwise a few nits to keep in mind for future cards.

2020-11-03 16:01 UTC, karzak commented on x/harvest/keeper/borrow.go
> +	moneyMarket, found := k.GetMoneyMarket(ctx, deposit.Amount.Denom)
One thing to keep track of is how many calls we are making to GetMoneyMarket per borrow. Don't see a need to refactor in this PR,  but that's probably the most expensive read operation we make, so minimizing those calls is a valid goal.

2020-11-03 17:43 UTC, denalimarsh commented on x/harvest/keeper/borrow.go
> +	depositsTotalUSDValue := sdk.ZeroDec()
Updated in https://github.com/Kava-Labs/kava/pull/711/commits/7ff59f455564b2504f7217bbb3aaa9747e1a348c

2020-11-04 14:26 UTC, karzak approved these changes

2020-11-05 17:36 UTC, merged