Harvest: interest rate model params
Kava-Labs/kava pull request #719
Opened 2020-11-12 20:34 UTC by denalimarsh

This PR adds the parameters for a money market's interest rate model. Interest rate models are stored in the module's store and updated in the begin blocker if they do not match the module's current parameters. The cmp package is used instead of reflect.DeepEqual for optimization. The cmp package searches for `Equal()` on the containing types and uses it to compare the objects, only falling back to reflect.DeepEqual as a last resort.

Add `interest_rate_model` to each money market in your genesis.json file or the chain will panic on start:
```bash
"interest_rate_model" : {
  "base_rate_apy": "0.05",
  "base_multiplier": "2",
  "kink": "0.85",
  "jump_multiplier": "10"
}
```

2020-11-12 22:00 UTC, karzak requested changes
Params look good - don't think the new dependency makes sense though - would just add an equality method.

2020-11-13 13:59 UTC, denalimarsh commented on x/harvest/keeper/interest.go
> +		if !cmp.Equal(model, mm.InterestRateModel) {
Added the custom equality method and removed the `gocmp` dep in https://github.com/Kava-Labs/kava/pull/719/commits/ed93221c292cbfd79b7729f4b432f650e925ca99

2020-11-13 15:40 UTC, denalimarsh commented on x/harvest/keeper/interest.go
> +func (k Keeper) ApplyInterestRateUpdates(ctx sdk.Context) {
Thought about it a bit and implemented a solution in https://github.com/Kava-Labs/kava/pull/719/commits/1426f4e5c0e99c44b84c585be9602dbe4fa864f1 that still only reads the module params once.

2020-11-13 15:51 UTC, karzak approved these changes

2020-11-13 15:51 UTC, merged