update cdp genesis state and migrations
Kava-Labs/kava pull request #738
Opened 2020-12-11 20:34 UTC by karzak

Blocked by #737 - review that first

2020-12-21 16:15 UTC, rhuairahrighairidh requested changes
In `cdp/genesis.go` ln 84, the total principle is calculated by summing the cdps' `TotalPrinciple()` but this won't include the interest accumulated since the cdp was last modified. So in moving from kava-5 to kava-6 some TotalPrincipal will be dropped.

I think either the raw TotalPrincipal amount needs to be stored in genesis, or `SynchronizeInterest` needs to be run on all cdps on export.

2020-12-21 22:20 UTC, karzak commented on x/cdp/keeper/deposit.go
> +	cdp = k.SynchronizeInterest(ctx, cdp)
Resolved in 25d09b7

2020-12-21 22:21 UTC, karzak commented
> In `cdp/genesis.go` ln 84, the total principle is calculated by summing the cdps' `TotalPrinciple()` but this won't include the interest accumulated since the cdp was last modified. So in moving from kava-5 to kava-6 some TotalPrincipal will be dropped.
> 
> I think either the raw TotalPrincipal amount needs to be stored in genesis, or `SynchronizeInterest` needs to be run on all cdps on export.

Good catch. Updated `GenesisState` to include a total principal argument, as it's no longer the case that CDP principal and total principal add up exactly.

2020-12-23 19:04 UTC, rhuairahrighairidh approved these changes
nice, looks good to me

2020-12-24 16:07 UTC, merged