Accrue Hard module rewards in multiple coin denoms
Kava-Labs/kava pull request #785
Opened 2021-02-01 12:59 UTC by denalimarsh

- [x] Implement multi reward types and update module params
- [x] Update keeper methods to init/accumulate/sync multiple reward denoms
- [x] Update tests so they compile (actual test implementation to be done in follow-on PR)

2021-02-01 20:28 UTC, karzak requested changes
Looks like everything working once those `!` were added - I managed to get a 'Accumulate' and 'Synchronize' test passing in `rewards_test.go`, so I think we're good to go on to next PR.

2021-02-01 20:28 UTC, karzak commented on x/incentive/keeper/rewards.go
> +			if foundUserRewardIndexIndex {
```suggestion
			if !foundUserRewardIndexIndex {
```

2021-02-01 20:28 UTC, karzak commented on x/incentive/keeper/rewards.go
> +			if foundFactorIndex {
```suggestion
			if !foundFactorIndex {
```

2021-02-01 20:28 UTC, karzak commented on x/incentive/keeper/rewards.go
> +			if foundUserRewardIndexIndex {
```suggestion
			if !foundUserRewardIndexIndex {
```

2021-02-01 20:28 UTC, karzak commented on x/incentive/keeper/rewards.go
> +			if foundFactorIndex {
```suggestion
			if !foundFactorIndex {
```

2021-02-02 10:02 UTC, denalimarsh commented on x/incentive/keeper/rewards.go
> +			if foundFactorIndex {
https://github.com/Kava-Labs/kava/pull/785/commits/a949c221d2020e8b4d8a366b01749dd403bf1f2c

2021-02-02 10:03 UTC, denalimarsh commented on x/incentive/keeper/rewards.go
> +			if foundUserRewardIndexIndex {
https://github.com/Kava-Labs/kava/pull/785/commits/a949c221d2020e8b4d8a366b01749dd403bf1f2c

2021-02-02 10:03 UTC, denalimarsh commented on x/incentive/keeper/rewards.go
> +			if foundFactorIndex {
https://github.com/Kava-Labs/kava/pull/785/commits/a949c221d2020e8b4d8a366b01749dd403bf1f2c

2021-02-02 10:03 UTC, denalimarsh commented on x/incentive/keeper/rewards.go
> +			if foundUserRewardIndexIndex {
https://github.com/Kava-Labs/kava/pull/785/commits/a949c221d2020e8b4d8a366b01749dd403bf1f2c

2021-02-02 16:17 UTC, merged