Add committee migrations
Kava-Labs/kava pull request #818
Opened 2021-02-11 19:23 UTC by karzak

2021-02-16 14:36 UTC, rhuairahrighairidh requested changes
`SubParamChangePermission.Allows(..` doesn't check the incoming param changes against the AllowedMoneyMarket permissions.

2021-02-16 14:36 UTC, rhuairahrighairidh commented on x/committee/types/permissions.go
> +	return allowed
I'd add `ReserveFactor` equality check in case we ever need to change it via committee.

2021-02-16 14:36 UTC, rhuairahrighairidh commented on x/committee/types/permissions.go
> +// Allows implement permission interface
nit: these methods don't implement the `types.Permission` interface (different arg types). Only the top level permission methods like `func (perm SubParamChangePermission) Allows(...` implements it

2021-02-16 15:09 UTC, rhuairahrighairidh commented
nit: There's no permissions for the new cdp params `KeeperRewardPercentage`, `CheckCollateralizationIndexCount`. But we might be able to get away without modifying them via committee.

2021-02-18 19:52 UTC, rhuairahrighairidh requested changes

2021-02-18 19:52 UTC, rhuairahrighairidh commented on migrate/v0_13/migrate.go
> +						newCP := v0_13committee.AllowedCollateralParam(cp)
Looks like go doesn't like the type cast to AllowedCollateralParam. Circleci doesn't run the migrate tests.
```suggestion
						newCP := v0_13committee.NewAllowedCollateralParam(
							cp.Type,
							cp.Denom,
							cp.LiquidationRatio,
							cp.DebtLimit,
							cp.StabilityFee,
							cp.AuctionSize,
							cp.LiquidationPenalty,
							cp.Prefix,
							cp.SpotMarketID,
							cp.LiquidationMarketID,
							cp.ConversionFactor,
							true,
							true,
						)
```

2021-02-18 19:52 UTC, rhuairahrighairidh commented on migrate/v0_13/migrate.go
> +			committees = append(committees, newStabilityCommittee)
```suggestion
			newStabilityCommitteePermissions = append(newStabilityCommitteePermissions, v0_13committee.TextPermission{})
			newStabilityCommittee.Permissions = newStabilityCommitteePermissions
			committees = append(committees, newStabilityCommittee)
```
linter caught this

2021-02-18 19:52 UTC, rhuairahrighairidh commented on migrate/v0_13/migrate_test.go
> +}
nit: hacky test to check no permissions were dropped
```suggestion
	require.Equal(t, len(oldGenState.Committees), len(newGenState.Committees))
	
	for i := 0; i < len(oldGenState.Committees); i++ {
		require.Equal(t, len(oldGenState.Committees[i].Permissions), len(newGenState.Committees[i].Permissions))
	}
	
	oldSPCP := oldGenState.Committees[0].Permissions[0].(v0_11committee.SubParamChangePermission)
	newSPCP := newGenState.Committees[0].Permissions[0].(v0_13committee.SubParamChangePermission)
	require.Equal(t, len(oldSPCP.AllowedParams), len(newSPCP.AllowedParams))
	require.Equal(t, len(oldSPCP.AllowedAssetParams), len(newSPCP.AllowedAssetParams))
	require.Equal(t, len(oldSPCP.AllowedCollateralParams), len(newSPCP.AllowedCollateralParams))
	require.Equal(t, len(oldSPCP.AllowedMarkets), len(newSPCP.AllowedMarkets))
}
```

2021-02-18 20:31 UTC, karzak commented on .circleci/config.yml
> +      - image: circleci/golang:1.15
If I recall the tests we're failing, but I think it was unrelated. Will push back to 1.13 and make sure there's no issue.

2021-02-19 12:50 UTC, rhuairahrighairidh approved these changes
looks good

2021-02-19 21:05 UTC, merged